import test from 'node:test';
import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createApp } from '../server/app.js';

test('automation API enforces owner, validates revisions and returns AI drafts without saving', async () => {
  const keys = ['INITIAL_ADMIN_PASSWORD', 'AUTOMATION_AI_BASE_URL', 'AUTOMATION_AI_API_KEY', 'AUTOMATION_AI_MODEL'];
  const previous = Object.fromEntries(keys.map(k => [k, process.env[k]]));
  process.env.INITIAL_ADMIN_PASSWORD = 'automation-test-123';
  for (const key of keys.slice(1)) delete process.env[key];
  const directory = await mkdtemp(join(tmpdir(), 'automation-api-'));
  const app = await createApp({ dbPath: join(directory, 'test.sqlite') });
  const server = createServer(app.callback());
  let provider;
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  const base = `http://127.0.0.1:${server.address().port}/api`;
  const request = async (path, method = 'GET', body, token) => {
    const response = await fetch(base + path, { method, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}) }, ...(body ? { body: JSON.stringify(body) } : {}) });
    return { status: response.status, body: await response.json() };
  };
  try {
    assert.equal((await request('/automations')).status, 401);
    const login = await request('/auth/login', 'POST', { username: 'admin', password: process.env.INITIAL_ADMIN_PASSWORD });
    const token = login.body.token;
    assert.ok(token);
    const initial = await request('/automations', 'GET', null, token);
    assert.equal(initial.status, 200);
    assert.equal(initial.body.aiConfigured, false);
    const automatic = await request('/tasks', 'POST', { title: '按规则分配' }, token);
    assert.equal(automatic.body.task.assigneeUserId, login.body.user.id);
    const unassigned = await request('/tasks', 'POST', { title: '明确不分配', assigneeUserId: '' }, token);
    assert.equal(unassigned.body.task.assigneeUserId, login.body.user.id);
    const rule = initial.body.rules[0];
    assert.equal((await request(`/automations/${rule.id}`, 'PUT', { ...rule, revision: 999 }, token)).status, 409);
    assert.equal((await request('/automation-sets', 'POST', { name: '外部成员', userIds: ['not-in-tenant'] }, token)).status, 400);
    const member = await request('/members', 'POST', { username: 'automation-reader', displayName: '测试成员', temporaryPassword: 'automation-test-123', role: 'engineer' }, token);
    assert.equal(member.status, 201);
    const memberLogin = await request('/auth/login', 'POST', { username: 'automation-reader', password: 'automation-test-123' });
    assert.equal((await request('/automations', 'GET', null, memberLogin.body.token)).status, 403);
    assert.equal((await request('/automations', 'POST', rule, memberLogin.body.token)).status, 403);
    assert.equal((await request(`/automations/${rule.id}/enabled`, 'PATCH', { enabled: false, revision: rule.revision }, memberLogin.body.token)).status, 403);
    assert.equal((await request(`/automations/${rule.id}/enabled`, 'PATCH', { enabled: false, revision: 999 }, token)).status, 409);
    assert.equal((await request(`/automations/${rule.id}/enabled`, 'PATCH', { enabled: 'false', revision: rule.revision }, token)).status, 400);
    const toggled = await request(`/automations/${rule.id}/enabled`, 'PATCH', { enabled: false, revision: rule.revision, source: '未完成的本地草稿', name: '不应覆盖' }, token);
    assert.equal(toggled.status, 200);
    assert.equal(toggled.body.rule.source, rule.source, 'toggle never saves local source');
    assert.equal(toggled.body.rule.name, rule.name);
    assert.equal(toggled.body.rule.enabled, false);
    assert.equal(toggled.body.rule.revision, rule.revision + 1);
    assert.equal((await request('/tasks', 'POST', { title: '关闭默认事件' }, token)).body.task.assigneeUserId, '');
    const restored = await request(`/automations/${rule.id}/enabled`, 'PATCH', { enabled: true, revision: toggled.body.rule.revision }, token);
    assert.equal(restored.status, 200);
    const legacySet = await request('/automation-sets', 'POST', { name: '可删除的旧集合', userIds: [login.body.user.id] }, token);
    assert.equal(legacySet.status, 201);
    const legacyRule = await request('/automations', 'POST', { name: '引用失效也可停用', enabled: true, source: '当 独立任务 创建时\n将 当前任务的执行者 设为 从 集合「可删除的旧集合」 随机选择一人' }, token);
    assert.equal(legacyRule.status, 201);
    await request(`/automation-sets/${legacySet.body.set.id}`, 'DELETE', null, token);
    const disabledBroken = await request(`/automations/${legacyRule.body.rule.id}/enabled`, 'PATCH', { enabled: false, revision: 1 }, token);
    assert.equal(disabledBroken.status, 200);
    assert.equal((await request(`/automations/${legacyRule.body.rule.id}/enabled`, 'PATCH', { enabled: true, revision: 2 }, token)).status, 400);
    assert.equal((await request(`/automations/${legacyRule.body.rule.id}/enabled`, 'PATCH', { enabled: true, revision: 1 }, token)).status, 409);
    const beforeAI = (await request('/automations', 'GET', null, token)).body.rules;
    const prompt = { request: '添加记录', source: rule.source };
    assert.equal((await request('/automations/ai', 'POST', prompt, token)).status, 503);
    const generated = '当 独立任务 创建时\n设 人员数组「工程师」 为 [成员「admin」]\n将 当前任务的执行者 设为 从 人员数组「工程师」 随机选择一人\n记录 「AI 草稿」';
    provider = createServer(async (req, res) => {
      let body = ''; for await (const chunk of req) body += chunk;
      assert.equal(JSON.parse(body).model, 'test-model');
      res.setHeader('Content-Type', 'application/json');
      res.end(JSON.stringify({ choices: [{ message: { content: generated } }] }));
    });
    await new Promise(resolve => provider.listen(0, '127.0.0.1', resolve));
    process.env.AUTOMATION_AI_BASE_URL = `http://127.0.0.1:${provider.address().port}/v1`;
    process.env.AUTOMATION_AI_API_KEY = 'test-only';
    process.env.AUTOMATION_AI_MODEL = 'test-model';
    const draft = await request('/automations/ai', 'POST', prompt, token);
    assert.equal(draft.status, 200);
    assert.equal(draft.body.source, generated);
    assert.deepEqual((await request('/automations', 'GET', null, token)).body.rules, beforeAI);
  } finally {
    if (provider) await new Promise(resolve => provider.close(resolve));
    await new Promise(resolve => server.close(resolve)); app.close();
    await rm(directory, { recursive: true, force: true });
    for (const key of keys) if (previous[key] === undefined) delete process.env[key]; else process.env[key] = previous[key];
  }
});
