const { contextBridge, ipcRenderer } = require('electron');

const invoke = (channel, ...args) => ipcRenderer.invoke(channel, ...args);
contextBridge.exposeInMainWorld('electronAPI', {
  platform: process.platform,
  pathToFileUrl: (value) => invoke('path:toFileUrl', value),
  selectFile: (options) => invoke('fs:selectFile', options),
  selectFolder: () => invoke('fs:selectFolder'),
  listDrives: () => invoke('fs:listDrives'),
  readDir: (value) => invoke('fs:readDir', value),
  listSupportedVideosInFolder: (value, options) => invoke('assets:listSupportedVideosInFolder', value, options),
  isSupportedVideoFile: (value) => invoke('assets:isSupportedVideoFile', value),
  readFileUtf8: (value) => invoke('fs:readFileUtf8', value),
  writeFileUtf8: (value, data) => invoke('fs:writeFileUtf8', value, data),
  writeFileBuffer: (value, data) => invoke('fs:writeFileBuffer', value, data),
  pathExists: (value) => invoke('fs:pathExists', value),
  copyFile: (source, target) => invoke('fs:copyFile', source, target),
  ensureDir: (value) => invoke('fs:ensureDir', value),
  emptyDir: (value) => invoke('fs:emptyDir', value),
  copyBundledVideoAssets: (value) => invoke('assets:copyBundledDefaults', value),
  getPath: (value) => invoke('app:getPath', value),
  backendStatus: () => invoke('backend:status'),
  getAutoUpdateState: () => invoke('autoUpdate:getState'),
  checkForAppUpdates: () => invoke('autoUpdate:check'),
  installDownloadedAppUpdate: () => invoke('autoUpdate:install'),
  scanMixRoot: (value) => invoke('assets:scanMixRoot', value),
  createMixCategoryFolder: (root, name) => invoke('assets:createCategoryFolder', root, name),
  openPath: (value) => invoke('shell:openPath', value),
  listMixCustomTemplates: () => invoke('mixTemplates:list'),
  saveMixCustomTemplate: (name, payload) => invoke('mixTemplates:save', name, payload),
  getMixCustomTemplate: (id) => invoke('mixTemplates:get', id),
  deleteMixCustomTemplate: (id) => invoke('mixTemplates:delete', id),
  defaultFontsDirectory: () => invoke('fonts:defaultDirectory'),
  defaultBgmDirectory: () => invoke('fonts:defaultBgmDirectory'),
  systemFontsDirectory: () => invoke('fonts:systemDirectory'),
  listFontFiles: (root, limit) => invoke('fonts:listDirectory', root, limit),
  dashscopeChatCompletions: (payload) => invoke('dashscope:chatCompletions', payload),
  syncReleaseScheduleMeta: (payload) => invoke('store:syncReleaseScheduleMeta', payload),
  syncPublishAccounts: (payload) => invoke('store:syncPublishAccounts', payload),
  onAutoPublishResult: (callback) => { const listener = (_event, value) => callback(value); ipcRenderer.on('release:autoPublishResult', listener); return () => ipcRenderer.removeListener('release:autoPublishResult', listener); },
  onMainLog: (callback) => { const listener = (_event, value) => callback(value); ipcRenderer.on('app:mainLog', listener); return () => ipcRenderer.removeListener('app:mainLog', listener); },
  onAutoUpdateState: (callback) => { const listener = (_event, value) => callback(value); ipcRenderer.on('autoUpdate:state', listener); return () => ipcRenderer.removeListener('autoUpdate:state', listener); }
});
